### ISSUE TITLE
Se solapan las pantallas de ajustes y créditos

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#1]
**1. Prioridad/Impacto:** bajo

**2. Plataforma:** PC

**3. Descripción:** en el menú principal, cuando se pulsa sobre el botón de ajustes, se puede pulsar sobre el botón de información sin haber salido previamente de la pantalla de configuración. Además, se solapan las dos pantallas, estando la pantalla de ajustes por encima de la de créditos.

**4. Pasos para reproducirlo:**
 - **Paso 1:** pulsar el botón de ajustes
 - **Paso 2:** pulsar el botón de información mientras la pantalla de ajustes sigue abierta.

![image](https://user-images.githubusercontent.com/61016923/143007691-9f70c27a-b12d-4448-ae85-461e10bbebb5.png)

![image](https://user-images.githubusercontent.com/61016923/143007647-661bf535-3bae-4d71-8d1b-da8dacefc643.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
