### ISSUE TITLE
Colisión con varios enemigos pequeños falla

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#10]
`Impacto:` Medio
`Entorno:` PC y Movil
`Descripción:` Cuando muchos enemigos pequeños te rodean, esas colisiones te desplazan al otro lado de donde estén ellos de repente.
`Pasos para reproducirlo:` Desconocido

**Comment by TheNidesRA** [comment]
No se ha podido reproducir este error correctamente. Se necesita algo más de especificación, ya sea una foto o un vídeo.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
