### ISSUE TITLE
[JUGABILIDAD] Jugador atrapado en el camión de helados

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#100]
Impacto: Crítico.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando se dispara a los demonios pequeños cerca de la camioneta y hay muchos, empiezan a empujar al personaje hacia dentro de la camioneta hasta que se queda atascado sin posibilidad de salir. No se puede seguir jugando en este estado. Incluso se muere cerca, también pasa eso.
Pasos para reproducirlo: Debes disparar cerca de la furgoneta y delante de varios enemigos pequeños.
![image](https://user-images.githubusercontent.com/72705329/143625070-4c3d3286-c259-4007-a740-2876ce781ab0.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/76365e5efef04918c4aab322b5018a74133644a2, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
