### ISSUE TITLE
El personaje seleccionado aparece en otras pantallas

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#11]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` Cuando se selecciona un personaje, su modelo sigue apareciendo en otros menús (Tienda, Personajes)
`Pasos para reproducirlo:` Pulsar muchas veces sobre el botón "CHOOSE" en el menú de selección de personajes y después pulsar sobre los botones "STORE" o "CHARACTERS"

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
