### ISSUE TITLE
Muerte lenta

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#12]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` A veces ocurre que aunque el jugador pierda toda la vida este no realiza la animación de morir hasta unos segundos después. La mayoría de veces ocurre por el fallo "Colisión con varios enemigos falla".
`Pasos para reproducirlo:` Desconocido.

**Comment by TheNidesRA** [comment]
No se ha podido reproducir este error correctamente. Se necesita algo más de especificación, ya sea una foto o un vídeo.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
