### ISSUE TITLE
Muros indestructibles en espacios del grid

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#13]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` Si colocas un muro en la segunda columna y al 4º y 5º fila, los enemigos pequeños detectan que el muro esta en medio y lo atacan. Sin embargo, no lo pueden destruir, y después de un rato, se dirigen hacia ti.  Alguno se puede quedar bugeado al lado del muro.
`Pasos para reproducirlo:` Se comenta arriba

**Comment by TheNidesRA** [comment]
No se ha podido reproducir este error correctamente. Se necesita algo más de especificación, ya sea una foto o un vídeo.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
