### ISSUE TITLE
Se pueden pulsar otros botones mientras la ventana de ajustes está abierta

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#14]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` Cuando la ventana de ajustes está abierta, se pueden pulsar sobre los otros botones que hay en el menú principal y acceder a sus correspondientes pantallas. Sin embargo, cuando se pulsa sobre "Play", se cierra la ventana de ajustes automáticamente.
`Pasos para reproducirlo:` "Paso 1: pulsar el botón de ajustes
Paso 2: pulsar cualquier otro botón de la interfaz"

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
