### ISSUE TITLE
Asignación aleatoria de una dirección

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#15]
`Impacto:` Alto
`Entorno:` PC y móvil
`Descripción:` De vez en cuando, cuando colocas un objeto en el campo el personaje se mueve hacia un lugar aleatorio sin parar aunque no se haya pulsado el botón. Cuando pulsas a otra dirección se mueve, pero cuando dejas de pulsar se sigue moviendo hacia el lugar anterior. Se le queda una dirección asignada. Se soluciona pulsando en cualquier parte activando el joystick.
`Pasos para reproducirlo:` Normalmente después de colocar una estructura.

**Comment by TheNidesRA** [comment]
Se han solucionado todos los problemas derivados del movimiento y del joystick en este commit final: https://github.com/TheNidesRA/FrozenFury/commit/796faabcd1bcf1e3141eb0c100d86074b69720f7

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
