### ISSUE TITLE
Dirección bloqueda

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#16]
`Impacto:` Alto
`Entorno:` PC y móvil
`Descripción:` Si selecciono una dirección con el dedo y directamente elijo otra se bloquea la dirección.
`Pasos para reproducirlo:` Se comenta arriba

**Comment by TheNidesRA** [comment]
Se han solucionado todos los problemas derivados del movimiento y del joystick en este commit final: https://github.com/TheNidesRA/FrozenFury/commit/462dffa6169cd43cade8dab4010e6081e759644e.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA

**Comment by TheNidesRA** [comment]
Se ha solucionado el error en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/519d71915d514ab562ae66de0d4a28f6aa31f7ea.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
