### ISSUE TITLE
No se puede mejorar una defensa

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#17]
`Impacto:` Alto
`Entorno:` PC y móvil
`Descripción:` Cuando una defensa se ha roto, no se puede reparar.
`Pasos para reproducirlo:` Pulsar sobre el botón de reparar

**Comment by TheNidesRA** [comment]
Se ha eliminado la opción de reparación de las estructuras puesto que no tenían uso alguno en la fase Beta. Se tomará en consideración volver a implementarla en caso de que los edificables se encuentren dañados.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
