### ISSUE TITLE
Posibilidad de quedar atrapado entre tus propias paredes

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#18]
`Impacto:` Crítico
`Entorno:` PC y móvil
`Descripción:` Te puedes quedar atrapado dentro de tus propias paredes ya que no se controla si el jugador esta o no esta en la posición en la que se ponen los objetos.
`Pasos para reproducirlo:` Colocar paredes en la posición el jugador

**Comment by TheNidesRA** [comment]
Desde el menú de mejora de construcciones, existe una opción de eliminar la estructura. Esta opción estaba presente en la beta pero no se indicaba correctamente a través de un tutorial.

Para la versión final del juego, se ha aclarado en el tutorial esta característica, devolviéndose un 50% del coste de construcción de la estructura borrada. De esta forma, el jugador podrá librarse de quedar atrapado entre cuatro paredes.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
