### ISSUE TITLE
No se pueden colocar cosntrucciones en mapa

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#19]
`Impacto:` Crítico
`Entorno:` Móvil
`Descripción:` No se pueden poner construcciones en el mapa rompiendo el juego. Entra en un modo de seleccionar espacio en el grid sin forma de volver a seleccionar ni colocar nada. Puedes empezar la ronda, pero cuando esta termina e intentas volver a colocar construcciones la construcción sigue en su sitio.
`Pasos para reproducirlo:` Es un error grave que no sabemos reproducir y que solo ha ocurrido una vez

**Comment by TheNidesRA** [comment]
No sabemos cómo reproducir el error exactamente. Una alternativa que se ha añadido es la posibilidad de cancelar la acción de construcción presionando una pequeña "X" que aparece por el mapa.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
