### ISSUE TITLE
Se pueden pulsar otros botones mientras la ventana de ajustes está abierta.

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#2]
1. **Prioridad/Impacto:** medio

2. **Plataforma:** PC

3. **Descripción:** cuando la ventana de ajustes está abierta, se pueden pulsar sobre los otros botones que hay en el menú principal y acceder a sus correspondientes pantallas. Sin embargo, cuando se pulsa sobre "Play", se cierra la ventana de ajustes automáticamente.

4. **Pasos para reproducirlo:**
- **Paso 1:** pulsar el botón de ajustes
- **Paso 2:** pulsar cualquier otro botón de la interfaz

![image](https://user-images.githubusercontent.com/61016923/143008580-aba76ee8-c208-4677-864b-74bd2d9569c7.png)

![image](https://user-images.githubusercontent.com/61016923/143008629-a3485184-b178-4439-a26c-8881cf4149d2.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
