### ISSUE TITLE
Los enemigos no atacan los muros cuando se bloquea su entrada 

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#20]
`Impacto:` Crítico
`Entorno:` PC y móvil
`Descripción:` Cuando se colocan muchos muros en la zona de generación de enemigos, siguen apareciendo pero al estar fuera de los límites del terreno jugable, no atacan el muro por lo que se quedan bloqueados moviéndose.
`Pasos para reproducirlo:` Colocar muros de forma que se bloquee la zona de generación de enemigos

**Comment by TheNidesRA** [comment]
Se ha solucionado el error en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/796faabcd1bcf1e3141eb0c100d86074b69720f7.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
