### ISSUE TITLE
Aparición de joystick en PC

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#21]
`Tipo:` Diseño
`Impacto:` Bajo
`Entorno:` PC
`Descripción:` El joystick del apartado móvil aparece cuando pulso en ordenador.
`Pasos para reproducirlo:` Pulsar con el rato en la pantalla del juego

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/73e2754b423eca44e7475d78aba5e3e2b1648b0e, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
