### ISSUE TITLE
Repetición inecesaria de entrada al menú de objetos

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#22]
`Tipo:`  Diseño
`Impacto:` Bajo
`Entorno:` PC
`Descripción:` Cada vez que quieres poner un objeto en el campo de juego se tiene que abrir el menú de elementos una y otra vez, como si fuera el último objeto que vas a colocar haciendo pesado el Gameplay.
`Pasos para reproducirlo:` Desconocido

**Comment by TheNidesRA** [comment]
Se precisa de más feedback externo de usuarios para implementar dicha característica. 

Tenemos en cuenta la sugerencia y se probará con más usuarios.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
