### ISSUE TITLE
Contexto inexistente sobre el mundo del juego

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#23]
`Tipo:` Diseño
`Impacto:` Bajo
`Entorno:` PC y móvil
`Descripción:` No hay ni un tutorial ni una introducción al mundo del juego, lo cual no sumerge tanto al jugador en la partida.
`Pasos para reproducirlo:` No lo hay

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/12f98faca1bbe6c040f155c8a014978267e7a0c8, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
