### ISSUE TITLE
Falta de indicaciones sobre atajos de teclado para los elementos consumibles

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#24]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Bajo

`Entorno:` PC

`Descripción:` Al pulsar botones al azar se pudo ver que los botones [1, 2, 3, 4] activan los objetos que se quiere del menú de elementos, pero no hay ningún tutorial o indicación para eso.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/12f98faca1bbe6c040f155c8a014978267e7a0c8, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
