### ISSUE TITLE
No hay cambio de sprite del botón "Start Round"

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#25]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Bajo

`Entorno:` PC

`Descripción:` El botón de "Start Round" no cambia cuando se comienza una ronda, lo que puede causar confusión.

**Comment by TheNidesRA** [comment]
Se ha solucionado el problema en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/691dc864897b299ee4d0df7156129b3c8a343959.

Ahora, el botón de Start Round desaparece al comenzar cada ronda.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
