### ISSUE TITLE
El ataque de enemigo negro grande desincronizado

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#26]
`Tipo:` Diseño
`Impacto:` Bajo
`Entorno:` PC y móvil
`Descripción:` El ataque del enemigo grande es lo suficientemente lento como para que el objeto al que este golpeando se destruya antes siquiera que la animación llegue al momento en el que lo toca
`Pasos para reproducirlo:` Ser golpeado por este enemigo a lo largo de la partida

**Comment by TheNidesRA** [comment]
El error se ha paliado modificando las estadísticas generales de los edificables y de los enemigos. También se ha ajustado los tiempos de las animaciones y añadidos vfx en la destrucción de estructuras.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
