### ISSUE TITLE
Iluminación de modelos 3D extraña

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#27]
`Tipo:`  Diseño
`Impacto:` Bajo
`Entorno:` PC y móvil
`Descripción:` El personaje de Torrine en el menú principal está muy poco iluminada, de modo que contrasta muy fuerte con el fondo y la iluminación de otros modelos y arte 2D del juego.
`Pasos para reproducirlo:` Ir al menú de selección de personajes

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/d2ded5bfab5984e018ce9b7bc6a89ea07d9158f5, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
