### ISSUE TITLE
Inexistencia de guía sobre los enemigos

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#28]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Bajo

`Entorno:` PC y móvil

`Descripción:` No hay especificaciones sobre las características de los enemigos, como por ejemplo, su nivel de vida mientras se juega la ronda.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/07de305f32c9326599139940aa6a27cf9ef94ea0, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
