### ISSUE TITLE
Diseño poco expresivo

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#29]
`Tipo:` Usabilidad
`Impacto:` Bajo
`Entorno:` Móvil
`Descripción:` El juego es poco expresivo y su diseño visual no es del todo agradable. Los objetos que hay no pegan con el terreno.
`Pasos para reproducirlo:` Entrar en el juego

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en los siguientes commits https://github.com/TheNidesRA/FrozenFury/commit/8b74a358f75b42d091c7c0ac0df0acd2f29a6492 y https://github.com/TheNidesRA/FrozenFury/commit/8aef4d3490e40bd26d0ed3366039f918b89b58dd así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
