### ISSUE TITLE
El personaje seleccionado aparece en otras pantallas

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#3]
1. **Prioridad/Impacto:** medio

2. **Plataforma:** PC

3. **Descripción:** Cuando se selecciona un personaje, su modelo sigue apareciendo en otros menús (Tienda, Personajes)

4. **Pasos para reproducirlo:** pulsar muchas veces sobre el botón "CHOOSE" en el menú de selección de personajes y después pulsar sobre los botones "STORE" o "CHARACTERS"

![image](https://user-images.githubusercontent.com/61016923/143010836-8dda1923-ae5e-4f7e-b75c-4f6239684dee.png)
![image](https://user-images.githubusercontent.com/61016923/143010893-18d0e1b6-9ef9-42a3-9cd0-46c78405bd9e.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
