### ISSUE TITLE
Confusión con el lugar por el que entran los enemigos

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#30]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Medio

`Entorno:` PC y móvil

`Descripción:` Si es la primera vez que juegas no sabes por dónde entrarán los enemigos, ya que no se indica, dando una sensación de frustración cuando ves que no aparecen por donde tu creías y rompiendo un poco la estrategia inicial del jugador.

**Comment by TheNidesRA** [comment]
La disposición del mapa se ha modificado y se puede intuir ahora correctamente el lugar en el que los enemigos aparecerán.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
