### ISSUE TITLE
Inexistencia de guía sobre los enemigos

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#31]
`Tipo:` Diseño
`Impacto:` Bajo
`Entorno:` PC y móvil
`Descripción:` No hay especificaciones sobre las características de los enemigos, como por ejemplo, su nivel de vida mientras se juega la ronda.
`Pasos para reproducirlo:` No hay

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/f2616a7d8c2cc37da37808f0d15e9cbc3ee7acee, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
