### ISSUE TITLE
Lentitud en las animaciones

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#32]
`Tipo:` Diseño
`Impacto:` Bajo
`Entorno:` PC y móvil
`Descripción:` Algunas animaciones se activan más tarde de lo que deberían a nivel visual. Por ejemplo: cuando uno de los monstruos destruye una pared, esta desaparece inmediatamente y a los segundos el monstruo hace la animación.
`Pasos para reproducirlo:` Jugar al juego

**Comment by TheNidesRA** [comment]
El error parece estar duplicado y ya se ha respondido en el siguiente comentario: https://github.com/TheNidesRA/FrozenFury/issues/26
