### ISSUE TITLE
Los elementos del interfaz son muy pequeños y se observan mal

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#33]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Medio

`Entorno:` Móvil

`Descripción:` Los elementos del interfaz son minúsculos y es difícil apreciarlos bien.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/4a90f04dc5e102eb3148833bf592f24e768aa19f, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
