### ISSUE TITLE
Tienda no implementada

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#35]
`Tipo:`  Diseño
`Impacto:` Bajo
`Entorno:` PC y móvil
`Descripción:` La tienda existe visualmente, pero no está implementada.
`Pasos para reproducirlo:` Abres la tienda en el juego

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2577ef17c4bf8635a7bdb812a4bba69751df2bab, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
