### ISSUE TITLE
Pérdida de interés en el personaje a causa de la posición de la cámara

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#36]
`Tipo:` Diseño
`Impacto:` Medio
`Entorno:` PC
`Descripción:` El diseño de personaje esta interesante pero en el juego no se le da valor por culpa de la cámara perdiendo un poco el sentido de las animaciones.
`Pasos para reproducirlo:` Jugar una partida

**Comment by TheNidesRA** [comment]
La idea principal es que el jugador tenga una visión completa de todos los elementos del escenario. Debido a la amplitud del mapa, es posible que los elementos que figuran en él puedan verse pequeños y sin el suficiente detalle, pero para la versión de salida del juego se mantendrá de esta forma.

Tenemos en cuenta esta sugerencia y veremos cómo se puede adaptar para versiones posteriores.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
