### ISSUE TITLE
Discordancia visual por cuadrícula verde 

### ISSUE THREAD

**Issue by SaYoTiTo** [TheNidesRA/FrozenFury#37]
`Tipo:` Diseño
`Impacto:` Medio
`Entorno:` PC
`Descripción:` Cuadrícula verde donde se posicionan los objetos desentona con los colores pastel del juego creando discordancia visual.
`Pasos para reproducirlo:` Colocar un objeto en el grid

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/8b74a358f75b42d091c7c0ac0df0acd2f29a6492, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
