### ISSUE TITLE
No hay retroalimentación

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#38]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Medio

`Entorno:` PC y móvil

`Descripción:` Cuando queda poco dinero para comprar construcciones, no hay nada que te diga que no puedes comprarlo. Tampoco hay algo que indique si queda poca vida.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/18a4d9e238dc3a7778733094c6bf5bd75c44bc06 , así que procedemos a cerrar este issue.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
