### ISSUE TITLE
La pantalla de victoria/derrota dura muy poco

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#39]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Medio

`Entorno:` PC y móvil

`Descripción:` Cuando se pierde una partida aparece una pantalla de derrota, pero solo durante unos segundos

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/944eb2e00827b3e63df82069f163e659cac519fc, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
