### ISSUE TITLE
Movimiento interrumpido con dos dedos en pantalla

### ISSUE THREAD

**Issue by sourdonny** [TheNidesRA/FrozenFury#4]
`Impacto:` Bajo
`Entorno:` Móvil 
`Descripción:` Si se pulsa con dos dedos a la vez el personaje comienza moverse de un lado a otro agitándose de vez en cuando.
`Pasos para reproducirlo:` 

1. Pulsar la pantalla del móvil con dos dedos a la vez durante el gameplay.

**Comment by TheNidesRA** [comment]
Se han solucionado todos los problemas derivados del movimiento y del joystick en este commit final: https://github.com/TheNidesRA/FrozenFury/commit/796faabcd1bcf1e3141eb0c100d86074b69720f7

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA

**Comment by TheNidesRA** [comment]
El issue se ha resuelto en el siguiente enlace: https://github.com/TheNidesRA/FrozenFury/issues/16
