### ISSUE TITLE
No existe tutorial o indicación de mejora de construcciones

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#40]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Alto

`Entorno:` Móvil

`Descripción:` No hay ninguna indicación de que se pueda arreglar o mejorar las construcciones. El modo mejorar construcciones funciona de vez en cuando

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/12f98faca1bbe6c040f155c8a014978267e7a0c8, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
