### ISSUE TITLE
Falta de tutorial

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#41]
`TIPO DE ERROR: USABILIDAD`

`Impacto:` Alto

`Entorno:` PC y móvil

`Descripción:` No hay una guía de cómo jugar

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/12f98faca1bbe6c040f155c8a014978267e7a0c8, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
