### ISSUE TITLE
Baja resolución en móvil

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#42]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Medio

`Entorno:` Móvil

`Descripción:` La resolución en el apartado movil es muy baja y se observan dientes de sierra en los contornos

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/4a90f04dc5e102eb3148833bf592f24e768aa19f, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
