### ISSUE TITLE
No hay indicación de comienzo de ronda

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#43]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Medio

`Entorno:` Móvil

`Descripción:` No hay forma de saber cuando empieza la ronda debido al falta de avisos. El botón que desparece es tan pequeño que ni siquieras te das cuenta.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/17267df8e95f728e146659fa8e959455a531c828, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
