### ISSUE TITLE
Poca optimización de menús de construcciones

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#44]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Medio

`Entorno:` PC y Móvil

`Descripción:` Al arrastrar objetos al grid, cuando dejas de pulsar, el objeto se queda ahí y para volver a moverlo hay que pulsar encima de él y darle al botón de mover. Se pierde mucho tiempo al hacer esto y hace pesado el gameplay.

**Comment by TheNidesRA** [comment]
No es necesario volver a pulsar sobre el objeto si se desea mover. Para volver a mover una estructura basta con pulsar el botón "Move" disponible en el menú desplegable disponible tras haber colocado la estructura.

Si hemos interpretado mal el error, por favor, precisamos de más información para reproducirlo.
