### ISSUE TITLE
No hay optimización en el borrado de construcciones 

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#45]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Medio

`Entorno:` PC y móvil

`Descripción:` En cuanto eliges una construcción y quieres coger otra de ellas, tienes que ponerla y despúes borrarla para poder volver a construir una cosa diferente

**Comment by TheNidesRA** [comment]
Lamentamos el malentendido. La confusión se podía deber a cómo se indicaban las distintas opciones en el menú de construcción. Para cancelar la construcción de una estructura bastaba con darle al botón de **Delete**, pero consideramos que lleva a malentendido.

Se ha modificado el texto del botón de **Delete** a la hora de confirmar la construcción de una estructura por un texto y un icono de **Cancel**.

El error se ha solucionado en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/522c8292fbeafce40222525386ad0528a2891dde

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
