### ISSUE TITLE
Conejo volador muy poderoso

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#46]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Medio

`Entorno:` PC y móvil

`Descripción:` El conejo volador revienta de dos golpes y es muy difícil de esquivar.

**Comment by TheNidesRA** [comment]
Se ha balanceado todo el contenido del juego en varios commits. El commit final es el siguiente: https://github.com/TheNidesRA/FrozenFury/commit/4e1fe6dad20e2be21f4867059c4a0008e4f8b18

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
