### ISSUE TITLE
Dificultad desbalanceada

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#48]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Alto

`Entorno:` PC y Móvil

`Descripción:` Puedes llegar varias rondas lejos sin poner ni un sólo objeto de construcción ni subir de nivel al personaje.

**Comment by TheNidesRA** [comment]
Se ha balanceado todo el contenido del juego en varios commits. El commit final es el siguiente: https://github.com/TheNidesRA/FrozenFury/commit/4e1fe6dad20e2be21f4867059c4a0008e4f8b18

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
