### ISSUE TITLE
No hay recompensa

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#49]
`TIPO DE ERROR: DISEÑO`

`Impacto:` Alto

`Entorno:` PC y móvil

`Descripción:` No hay recomenpsa por ganar o hacer el intento. Al terminar el juego no hay ni sistema de puntuación ni nada que recompense el esfuerzo del jugador.

**Comment by TheNidesRA** [comment]
Ahora se proporcionan 200 monedas * nº ronda alcanzada cuando ganas la partida!

La sugerencia se ha implementado en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/7f90474aed758942f94630e791b485c73f33bf31

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
