### ISSUE TITLE
No se ven los disparos del personaje Coneman

### ISSUE THREAD

**Issue by sourdonny** [TheNidesRA/FrozenFury#5]
`Impacto:` Medio
`Entorno:` PC
`Descripción:` Cuando Coneman dispara no se ve la bala.
`Pasos para reproducirlo:`

1. Elegir a Coneman en el menú "CHARACTERS"
2. Jugar con Coneman en el gameplay

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/19bb147b695f18b6ee9c7027f853f9e10cd9c39b, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
