### ISSUE TITLE
Solapamiento de sonido en el menú principal

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#50]
`TIPO DE ERROR: SONIDO`

`Impacto:` Bajo

`Entorno:` PC

`Descripción:` En el menú principal despues de escuhar un rato da la sensación de que dos canciones estan sonando a la vez.

**Comment by TheNidesRA** [comment]
Respecto a este problema, así es el tema del menú principal. Tendremos esta sugerencia en cuenta para posibles nuevos temas para el juego. ¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
