### ISSUE TITLE
El inicio de la ronda no se avisa de forma sonora

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#51]
`TIPO DE ERROR: SONIDO`

`Impacto:` Bajo

`Entorno:` PC

`Descripción:` No existe ningún sonido que indique el inicio de la ronda lo que puede llevar a confusión.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/17267df8e95f728e146659fa8e959455a531c828, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
