### ISSUE TITLE
No hay canción de victoria ni de derrota

### ISSUE THREAD

**Issue by miniponti** [TheNidesRA/FrozenFury#52]
`TIPO DE ERROR: SONIDO`

`Impacto:` Bajo

`Entorno:` PC y móvil

`Descripción:` No hay música para cuando el jugador termina una partida, ya sea habiendo ganado o perdido.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/8b0604aad31c3f70feeceba8ed98c813f1e99964, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
