### ISSUE TITLE
[USABILIDAD] Dentro de ajustes puedes pulsar botones de fuera de la pantalla.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#53]
**Impacto**: Bajo.
**Plataforma o entorno:** PC/Móvil, Chrome/Mozilla.
**Descripción:** El menú de ajustes permite pulsar otros botones como la tienda, los personajes o los créditos. Al pulsar estos botones, el menú de opciones se queda encima del menú pulsado.
**Pasos para reproducirlo:** Abrir el menú de opciones y pulsar el botón de otro menú.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
