### ISSUE TITLE
[ESTÉTICA] Torrine en el menú de personajes está flotando. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#54]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción:** El personaje de la chica, en su menú de selección aparece por encima de la plataforma que simula el suelo.
**Pasos para reproducirlo:** Abrir el menú de personajes, seleccionar al personaje Torrine.
![image](https://user-images.githubusercontent.com/72705329/143624069-8c8ea6c1-a44f-49f3-9045-fbf99bba7351.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/d97df90024a35dc37b09e12d1bbcd9e2e9685e33, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
