### ISSUE TITLE
[ESTÉTICA] EL loop del personaje principal no está bien hecho en los pies

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#55]
**Impacto**: Bajo.
**Plataforma o entorno:** PC/Móvil, Chrome/Mozilla.
**Descripción:** Si te fijas en la animacion de Ice Cream Man, descubres que los pies se mueven de su punto base.
**Pasos para reproducirlo:** Abrir el menú de personajes, seleccionar la del personaje principal y observar los pies.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/44e0b872a2dd29d58ac87c0c29af81a9fbcf07fd, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
