### ISSUE TITLE
[ESTÉTICA] En la compra de niveles, el sprite de ladrillos está mal escalado. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#56]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción**: El sprite que indica que tiene mejorar los ítems, está mal escalado.
**Pasos para reproducirlo:** Abrir el juego, darle a una partida y colocar cualquier objeto, en ese panel aparece el sprite.
![image](https://user-images.githubusercontent.com/72705329/143624114-224baad6-bf79-4b40-b7a9-078eeaebcc3e.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/691dc864897b299ee4d0df7156129b3c8a343959, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
