### ISSUE TITLE
[USABILIDAD] Grid del escenario

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#57]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción**: El tablero que aparece al para construir estructuras queda como superpuesto en el mapa y no integrado en él. además, queda desplazado a la izquierda y el tablero no se ajusta al mapa. 
**Pasos para reproducirlo:** Comprar una estructura.
![image](https://user-images.githubusercontent.com/72705329/143624138-ea842aba-dfd9-47f9-9190-a302f3986cb2.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/8b74a358f75b42d091c7c0ac0df0acd2f29a6492, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
