### ISSUE TITLE
[ESTÉTICA] Sacar los elementos del grid se quedan visibles

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#58]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción**: Al intentar colocar un elemento fuera del grid, automáticamente ese elemento se va a la parte inferior izquierda. Esto genera problema con pantallas de resoluciones distintas ya que según la pantalla con la que se juegue se ve más objeto o menos y no desaparece.
**Pasos para reproducirlo:** Comprar la estructura, moverla fuera del grid dentro de una partida.
![image](https://user-images.githubusercontent.com/72705329/143624166-4a680134-03b4-448a-ade8-3cb520488c0c.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/3d48d9cfa4296951fae72370d318ee07945b61fa, así que procedemos a cerrar este issue.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
