### ISSUE TITLE
[USABILIDAD] Indicar si los objetos son atravesables. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#59]
**Impacto**: Bajo.
**Plataforma o entorno:** PC/Móvil, Chrome/Mozilla.
**Descripción**: El jugador no puede atravesar los muros de galletas al igual que hace con el resto de las estructuras. Sería idóneo indicarlo previamente.
**Pasos para reproducirlo**: --

**Comment by TheNidesRA** [comment]
Implementaremos la característica si se precisa tras obtener más feedback de otros usuarios.

Tenemos en cuenta la sugerencia pero no se implementará para la salida del juego.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
