### ISSUE TITLE
No hay guardado de los ajustes entre menú principal y juego

### ISSUE THREAD

**Issue by sourdonny** [TheNidesRA/FrozenFury#6]
`Impacto:` Medio
`Entorno:` PC
`Descripción:` Si cambias el volumen en la pantalla inicial y después pasas a los ajustes dentro del gameplay los valores de sonido no se guardan.

1. Abrir el menú de ajustes
2. Cambiar valores de volumen
3. Entrar a la escena de juego

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/c31c29cf014c550b2f5bbee87baa0d33169b0f85, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
