### ISSUE TITLE
[SONIDO] Feedback del volumen de los SFX. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#60]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción**: No se puede comparar el volumen de los SFX para controlar su volumen óptimamente.
**Pasos para reproducirlo**: subir o bajar el volumen de los sonidos dentro del juego.

**Comment by TheNidesRA** [comment]
Se ha solucionado el problema añadiendo un botón para comprobar el volumen de los SFX en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/d8e27bc073cad0090fe762c1475ba98d2fd3b7b7.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
