### ISSUE TITLE
[USABILIDAD] Indicar personaje actual.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#61]
**Impacto**: Bajo.
**Plataforma o entorno:** PC/Móvil, Chrome/Mozilla.
**Descripción:** EL juego solo indica que personaje está usando el jugador en la pantalla inicial. Sin embargo, cuando se desea comprar un personaje o una skin no se deja claro cuál de los tres tiene en las UI.
**Pasos para reproducirlo:** Seleccionar otro personaje en la pantalla de personajes.

**Comment by TheNidesRA** [comment]
La descripción del error y el título resultan algo confusas y no sabemos muy bien con qué se corresponde el issue. Necesitamos algo más de información para poder corregir el error.

Creemos que con la tienda implementada correctamente (indicándose los personajes y skins que se tienen comprados) se deberían solucionar este tipo de errores.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
