### ISSUE TITLE
[USABILIDAD] Feedback sonoro en acciones del jugador y de los enemigos

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#62]
**Impacto**: Bajo.
**Plataforma o entorno:** PC/Móvil, Chrome/Mozilla.
**Descripción:** Cuando los enemigos dañan, mueren, dañan la furgoneta, entre otros, no se reproduce ningún sonido y genera que no se sea consciente de lo que pasa.
**Pasos para reproducirlo:** Jugar una partida.

**Comment by TheNidesRA** [comment]
Se han introducido muchos más sonidos para mejorar la experiencia en el juego. En el siguiente commit se pueden ver los últimos que se han añadido en el juego https://github.com/TheNidesRA/FrozenFury/commit/78d6bfe6ed7d6be19110886ccc2069e5414280c5

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
