### ISSUE TITLE
[USABILIDAD] Poca información sobre el rango de las estructuras y el personaje

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#63]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción:** Al crear o mejorar una estructura o al usar el personaje, se desconoce el rango de ataque que tienen y hasta donde son capaces de llegan. El único indicativo es el valor de rango, pero es insuficiente ya que visualmente no se sabe las distancias de ataque, el rango que protegen las estructuras o incluso si una estructura puede defender 360 grados. Además, tampoco aparecen la vida de estas estructuras para saber cuándo deberían ser mejoradas ni si son dañadas por enemigos aéreos o el nivel a la que está la estructura.
**Pasos para reproducirlo**: Crear o mejorar estructuras.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/544b502cfc51337cd00de41d0f080645acad3e19, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
