### ISSUE TITLE
[JUGABILIDAD] No se puede rotar una estructura en diagonal. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#64]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción**: Las estructuras no se pueden rotar en diagonal, lo que genera confusión entre la disposición del tablero y el camino que siguen los enemigos desde su punto de aparición hasta la camioneta, que es diagonal.  
**Pasos para reproducirlo:** Construir una estructura.

**Comment by TheNidesRA** [comment]
Los edificables podrán rotar únicamente siguiendo la forma cuadrada de las distintas casillas del grid. Rotar en diagonal no se ha contemplado como mecánica puesto que, entre otras cosas, las torretas girarán automáticamente cuando detectan un enemigo en su rango de visión.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
