### ISSUE TITLE
[COMPATIBILIDAD] Textos o imágenes muy pequeños. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#65]
**Impacto**: Bajo.
**Plataforma o entorno**: Móvil, Chrome/Mozilla.
**Descripción**:  Cuando se juega en móvil, hay ciertos textos o imágenes que se ven muy pequeños. Por ejemplo, en la tienda, en la sección de skins, cada una de las opciones se lee muy mal porque la letra es muy pequeña. Durante el juego, las gominolas y la vida de la caravana apenas se ven, al igual que el botón de "Start Round"
**Pasos para reproducirlo**: Jugar en móvil.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/4a90f04dc5e102eb3148833bf592f24e768aa19f, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
