### ISSUE TITLE
[USABILIDAD] No se puede mover y rotar a la vez.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#66]
Impacto: Bajo.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Es un error menor, pero hace que la navegación durante la construcción de estructuras sea menos fluida y más pesada. Debería una manera de poder rotar la estructura mientras la colocas y no tener que hacerlo siempre en dos pasos.
Pasos para reproducirlo: comprar una estructura y mejorarla.

**Comment by TheNidesRA** [comment]
En el tutorial ahora se indican los shortcuts de teclado correspondientes para poder llevar a cabo estas acciones. Solo se podrán hacer en PC.

La sugerencia se ha solucionado en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/336bb16aa3bc20122bc8c2b061d2fd1c505aed94.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
