### ISSUE TITLE
[ESTÉTICA] EL loop de animación del helado

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#67]
**Impacto**: Bajo.
**Plataforma o entorno**: PC/Móvil, Chrome/Mozilla.
**Descripción**: La animación de este personaje, cuando está andando en medio de una partida se nota que el loop no empieza y termina en el mismo sitio.
**Pasos para reproducirlo:** ver animación del helado en partida.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/44e0b872a2dd29d58ac87c0c29af81a9fbcf07fd, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
