### ISSUE TITLE
[SONIDO] Los sliders no son persistentes

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#68]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Al quitar el sonido en los ajustes para jugar una partida, si se vuelve al menú de ajustes, los sliders están de nuevo en el medio, mientras que el juego sin sonido. Cuando los mueves se reestablece el valor, pero se hace confuso si no los tocas de nuevo.
Pasos para reproducirlo: quitar el sonido del juego, jugar una partida y volver al menú de opciones.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/c31c29cf014c550b2f5bbee87baa0d33169b0f85, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
