### ISSUE TITLE
[JUGABILIDAD] Mover y rotar estructuras como mecánica. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#69]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando se construye una estructura, una vez finalizada la compra, no te da la opción de moverla o rotarla en un futuro. Para mejorar la dinámica de juego, estás mecánicas deberían implementarse, ya sea pagando chuches o de manera gratuita. Debería de existir la opción de rotar por lo menos. La de mover podría ponerse pagando, para que estuviese bien balanceada, pero debe existir la opción. Además, un mensaje de confirmación no estaría de más ya que es una acción de no retorno.
Pasos para reproducirlo: Modificar una estructura después de ser comprada.

**Comment by TheNidesRA** [comment]
La mecánica principal del juego gira en torno a la correcta y estratégica colocación de las estructuras en el grid del juego. Es importante pensar bien el lugar del mismo en el que se vaya a colocar puesto que la estructura se mantendrá en él durante todo su tiempo de vida. Además, ya que se permite el movimiento del jugador, es en parte tarea del mismo defender estos edificables con sus propios disparos.
No se ha planteado a nivel de diseño de gameplay la opción de poder moverlos puesto que hay otros elementos de juego (como mejoras o la opción de defenderlas con el jugador ya mencionadas) que hacen que no sea necesario.

No obstante, tenemos en cuenta esta sugerencia y recogeremos más retroalimentación con otras pruebas con usuarios externos.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
