### ISSUE TITLE
Atascado entre paredes

### ISSUE THREAD

**Issue by sourdonny** [TheNidesRA/FrozenFury#7]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` Te puedes encerrar tú solo con la construcción de las paredes. Probablemente porque no se tiene en cuenta o no se detecta la posición del personaje.
`Pasos para reproducirlo:`

1. Poner paredes alrededor del personaje a modo de jaula

**Comment by TheNidesRA** [comment]
El Issue se encuentra duplicado, se ha cerrado en el siguiente enlace: https://github.com/TheNidesRA/FrozenFury/issues/17
