### ISSUE TITLE
[ESTÉTICA] El loop de animación de Torrine

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#70]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: En la pantalla del Torrine, se puede observar como el loop de su mano izquierda está mal realizado y aparece como un pequeño movimiento que al verlo en el menú principal resulta molesto.
Pasos para reproducirlo: Seleccionar al personaje Torrine.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/44e0b872a2dd29d58ac87c0c29af81a9fbcf07fd, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
