### ISSUE TITLE
[ESTÉTICA] Baja resolución en dispositivos móviles.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#71]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: En dispositivos móviles, la resolución baja considerablemente haciendo que el juego se vea borroso. Una posible solución es poner los sprites como potencias de 2.
Pasos para reproducirlo: jugar a Frozen Fury en móvil.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/4a90f04dc5e102eb3148833bf592f24e768aa19f, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
