### ISSUE TITLE
[ESTÉTICA] La animación del personaje principal no escala a la velocidad.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#72]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando no se mueve el joystick del movimiento del personaje al máximo, este personaje no genera animaciones, simplemente parece que este flotando por el escenario.
Pasos para reproducirlo: poner el joystick del movimiento a mitad del círculo dentro de una partida. 
![image](https://user-images.githubusercontent.com/72705329/143624626-b0b57895-3cac-47c6-9bb4-ccd66304a477.png)

**Comment by TheNidesRA** [comment]
Cuando el joystick se encuentra en posiciones intermedias, las animaciones del personaje se mezclan entre el Idle del mismo y la propia animación de movimiento. Una opción para solucionar el issue sería establecer el valor máximo de movimiento en todo momento cuando se mueve el joystick, pero se condicionaría a no poder mover el personaje de forma más lenta en dispositivo móvil.

Debemos hacer más pruebas con usuarios y recibir retroalimentación sobre ello pero no contamos con el tiempo suficiente. Tenemos en cuenta el problema y lo trataremos de solucionar lo antes posible.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
