### ISSUE TITLE
[PROGRAMACIÓN] Al construir un elemento, el personaje a veces se mueve solo. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#73]
Impacto: Medio
Plataforma o entorno: PC/Móvil, Chrome/Mozilla
Descripción: A veces al crear edificaciones el jugador empieza a moverse solo hasta que llega a una zona del borde izquierdo del mapa. 
Pasos para reproducirlo: Mover al personaje, estar un tiempo dentro del menú de compra de objetos y colocarlo.

**Comment by TheNidesRA** [comment]
Se han solucionado todos los problemas derivados del movimiento y del joystick en este commit final: https://github.com/TheNidesRA/FrozenFury/commit/462dffa6169cd43cade8dab4010e6081e759644e.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
