### ISSUE TITLE
[JUGABILIDAD] Todos los enemigos aparecen del mismo lado

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#74]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla
Descripción: Al inicio de cada ronda, los enemigos aparecen todos desde un mismo sitio. Esto hace que la forma del grid no tenga sentido y, además, limite la experiencia de juego.
Pasos para reproducirlo: jugar una ronda.

**Comment by TheNidesRA** [comment]
Lamentablemente, no podremos añadir más mapas de cara a la versión final del juego. Está en proceso el modelado de nuevos mapas que se incluirán en futuras versiones de Frozen Fury donde la aparición de los enemigos en el mapa variará:

- Único punto de respawn de enemigos.
- Múltiples puntos de respawn de enemigos.
- Desplazamiento del objetivo principal al centro del mapa con múltiples puntos de respawn de enemigos.

Tememos en cuenta esta sugerencia para futuras implementaciones.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
