### ISSUE TITLE
[PROGRAMACIÓN] Colliders donde no hay objetos. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#75]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Al jugar una partida, da igual con el personaje que se haga, si el jugador se acerca a los bordes del mapa se chocará con elementos invisibles. O incluso cuando hay objetos cerca, el collider no está bien ajustado.
Pasos para reproducirlo: Jugar una partida y acercarse a los bordes del mapa.

**Comment by TheNidesRA** [comment]
Se han redistribuido los elementos del mapa para evitar la sensación de que el jugador se colisiona con objetos invisibles. 
Se pueden ver los cambios en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/a734cc3437d91b3a9cb9b6b2ffbba4f9a00b0d02

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
