### ISSUE TITLE
[ESTÉTICA] Toon shading del fondo 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#76]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: El shader que se usa dentro del juego, al no aplicarse a todo el escenario (elementos interactuables, estructuras, enemigos o personajes) hace que el jugador se pueda confundir con esos elementos y desentona con la estética del resto de objetos.
Pasos para reproducirlo: jugar una partida.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/d2ded5bfab5984e018ce9b7bc6a89ea07d9158f5, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
