### ISSUE TITLE
[USABILIDAD] Avisar de las acciones de no retorno

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#77]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Si al estar dentro de una partida, el jugador decide salir al menú principal, el juego no avisa con que pierde todo el proceso que ha conseguido hasta ese momento. Se agradecería un mensaje notificando la perdida de datos.
Pasos para reproducirlo: Jugar una partida, ganar una ronda y volver al menú principal.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/cd26aa367e7b0013c05881698f327fb8d839d26e, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
