### ISSUE TITLE
[USABILIDAD] Es un mapa muy grande para un móvil.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#78]
Impacto: Medio.
Plataforma o entorno: Móvil, Chrome/Mozilla.
Descripción: Durante una partida de móvil, los detalles del juego como los personajes, estructuras o enemigos se ven demasiado pequeños. 
Pasos para reproducirlo: Jugar una partida en móvil.

**Comment by TheNidesRA** [comment]
Creemos que el problema está fuertemente condicionado por la calidad gráfica del juego en dispositivos móviles y su baja resolución. Con los nuevos ajustes establecidos y subidos en el commit https://github.com/TheNidesRA/FrozenFury/commit/4a90f04dc5e102eb3148833bf592f24e768aa19f debería visualizarse todo con una mejor calidad.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
