### ISSUE TITLE
[USABILIDAD] Vida de la camioneta.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#79]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: La manera en la que la vida de la camioneta de helados está representada en la partida es confusa ya que parece un tipo de moneda del juego. Se debería cambiar por algo menos similar a la moneda. 
Pasos para reproducirlo: Jugar una partida y observar la vida de la camioneta.

**Comment by TheNidesRA** [comment]
Tomamos en cuenta la retroalimentación para cambiar estas características en posibles actualizaciones del juego, no obstante, esto no se implementará para la versión de salida.

Para reforzar el concepto, se ha implementado un tutorial en el menú principal donde se puede ver el propósito de los iconos que se muestran en pantalla. Esto se puede ver en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/a372014d5525fb4a60274855bd268e5ac15adb8f

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
