### ISSUE TITLE
Atascado fuera del mapa de juego

### ISSUE THREAD

**Issue by sourdonny** [TheNidesRA/FrozenFury#8]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` Los enemigos te pueden empujar fuera del mapa cuando mueres cerca de los límites del mapa.
`Pasos para reproducirlo:`

1. Posicionarse cerca de los límites del mapa
2. Morir y esperar a revivir

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/a734cc3437d91b3a9cb9b6b2ffbba4f9a00b0d02, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
