### ISSUE TITLE
[JUGABILIDAD] Al eliminar una estructura, no te dan monedas de vuelta.  

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#80]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando se elimina una estructura no se recibe nada a cambio, solo se elimina. En los tower defense, se dan siempre monedas a cambio, de tal manera que no es una acción rentable normalmente, pero que pueden venir bien en momentos específicos.
Pasos para reproducirlo: Eliminar una estructura creada anteriormente.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/76b3fe26b059205586e005980ff2e47e4a4f6c12, así que procedemos a cerrar este issue. Ahora, se devuelve un 50% del coste de la construcción correspondiente al borrarse.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
