### ISSUE TITLE
[USABILIDAD] Navegación en las estructuras poco intuitiva

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#81]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando estás en modo construcción, para ir hacia atrás y no poner una estructura, se tiene que eliminar, por ejemplo. Y cuando se mejora una, para volver hacia atrás tienes que pulsar al OK. Esto genera destruir estructuras sin querer, por ejemplo, porque no hay pantalla de confirmación.
Pasos para reproducirlo: Ir al modo construcción y salir, mejorar arma y salir.

**Comment by TheNidesRA** [comment]
Creemos que podía generar confusión por cómo se indica en la UI. Sí se puede cancelar la acción de construir una estructura pero estaba mal indicado en el menú de la estructura. Se ha modificado la opción de **Delete** a una opción de **Cancel** para un mayor entendimiento.

Lamentamos el malentendido.

El problema se ha solucionado en el siguiente commit: https://github.com/TheNidesRA/FrozenFury/commit/522c8292fbeafce40222525386ad0528a2891dde

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
