### ISSUE TITLE
[USABILIDAD] El botón de empezar ronda

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#82]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: El botón de comenzar ronda no cambia cuando es pulsado, de manera que se facilita a saber cuándo empieza la ronda y cuando acaba. La única manera de adivinarlo es gracias a que no hay enemigos en la pantalla. El botón debería desaparecer o cambiar dentro de la ronda.
Pasos para reproducirlo: Entrar a una partida y comenzar una ronda con el botón 'Start Round'

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/691dc864897b299ee4d0df7156129b3c8a343959, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
