### ISSUE TITLE
[COMPATIBILIDAD] Icono pantalla completa.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#83]
Impacto: Medio.
Plataforma o entorno: PC, Chrome/Mozilla.
Descripción: AL iniciar el juego en ordenador, por defecto, se juega sin pantalla completa y el botón que indica hacer la pantalla grade apenas se percibe.
Pasos para reproducirlo: Abrir el juego sin pantalla completa.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema cambiando algunos parámetros en nuestra página de [Frozen Fury](https://thenides-ra.itch.io/frozen-fury), el día 12 se podrá ver el cambio. Procedemos a cerrar el problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
