### ISSUE TITLE
[CONFORMIDAD] Fallo en la iluminación del pelo de Torrine. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#84]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: En el menú de selección de personaje y en el menú principal, el pelo de Torrine se ve negro. Se trata de un bug de iluminación bastante claro. Mientras juegas con ella dentro de la partida no ocurre este error.
Pasos para reproducirlo: Seleccionar a Torrine.
![image](https://user-images.githubusercontent.com/72705329/143624827-8440cd75-99fa-46d2-a852-8a84224332bd.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/8aef4d3490e40bd26d0ed3366039f918b89b58dd, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
