### ISSUE TITLE
[CONFORMIDAD] Los disparos de la catapulta apenas se ven. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#85]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando se pone un muro por delante de la catapulta, las balas de cereza dejan de aparecer.
Pasos para reproducirlo: Construir una catapulta detrás del muro.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/fa53ec2a341f40147f8057bc0defcae393ba38f9, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
