### ISSUE TITLE
[PROGRAMACIÓN] Personaje en la tienda

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#86]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Al seleccionar un personaje y rápidamente ir a la tienda, el personaje se verá en mitad de la tienda.
Pasos para reproducirlo: Ir a selección de personajes, elegir uno, al acabar la animación y estar en el menú principal, ir a la tienda y aparece el modelo 3D.
![image](https://user-images.githubusercontent.com/72705329/143624859-d9d3a8c7-2bf2-4799-b493-539ffb76d549.png)

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2189f485d8d268ff6279fb1a5b042997c1816b22, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
