### ISSUE TITLE
[USABILIDAD] El joystick aparece a pesar de estar utilizando los controles del teclado.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#87]
Impacto: Medio.
Plataforma o entorno: PC, Chrome/Mozilla.
Descripción: Probando el juego en el PC, existe la posibilidad de jugar con teclas y con el joystick. Al jugar con el joystick, se complica el resto de las mecánicas del juego, como plantar edificaciones y mejorarlas.
Pasos para reproducirlo: Usar el ratón en una partida.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/73e2754b423eca44e7475d78aba5e3e2b1648b0e, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
