### ISSUE TITLE
[JUGABILIDAD] Velocidad de los enemigos

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#88]
Impacto: Medio.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Cuando en el juego aparecen muchos enemigos, la velocidad de estos se reduce. Además, cuanto más alejado se encuentre el personaje, más lento se mueven.
Pasos para reproducirlo: Esperar a una ronda donde aparezcan muchos enemigos y alejarse. Si se logra el bug de la camioneta, se observa mejor.

**Comment by TheNidesRA** [comment]
No hemos sabido interpretar correctamente el problema por falta de detalles. Interpretamos que el problema que se comenta es el bug en el que el jugador se puede ocultar dentro de las torretas y, de esta forma, los enemigos se traban en el mapa y se paran. Dicho error se ha solucionado en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/f765bcb29c4bcb792c652a17cc92bffe0cb33ab7

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
