### ISSUE TITLE
[JUGABILIDAD] No hay tutoriales

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#89]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Dentro del juego no existe ningún tutorial ni instrucciones que indiquen que hay que hacer, cuando se empieza el juego por primera vez crea confusión. La información en el itch.io es útil pero insuficiente, se echa en falta mucha más, además que puede haber jugadores que no quieran leerlo.
Pasos para reproducirlo: Comenzar a jugar.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/12f98faca1bbe6c040f155c8a014978267e7a0c8, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
