### ISSUE TITLE
Estar atascado fuera del mapa te da inmortalidad

### ISSUE THREAD

**Issue by sourdonny** [TheNidesRA/FrozenFury#9]
`Impacto:` Medio
`Entorno:` PC y móvil
`Descripción:` Si te quedas fuera del mapa con el bug anterior puedes quedarte en un punto en el que los enemigos no te pueden matar, pero tu a ellos sí, haciendo que no puedas morir. Este punto está detrás del camión de los helados.
`Pasos para reproducirlo:` Desconocido

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/a734cc3437d91b3a9cb9b6b2ffbba4f9a00b0d02, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
