### ISSUE TITLE
[JUGABILIDAD] Falta de regeneración de la vida del personaje. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#90]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: No existe una manera de regenerar la vida del personaje durante la partida, tarda mucho en resucitar y la única manera de conseguir más vida es mejorar al personaje una vez terminada la ronda.  
Pasos para reproducirlo: Jugar una ronda y ser herido.

**Comment by TheNidesRA** [comment]
Tomamos en cuenta la retroalimentación para añadir la mecánica en posibles actualizaciones del juego, no obstante, esto no se implementará para la versión de salida. 

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
