### ISSUE TITLE
[USABILIDAD] Feedback visual en las acciones del jugador y de los enemigos

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#91]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla 
Descripción: Cuando el jugador hace alguna acción como disparar, ser dañado o matar a un enemigo hay poco feedback visual. Con los enemigos esto se multiplica, solo se sabe que están haciendo daño por la barra de vida del jugador. Lo mismo pasa cuando mueren, cuando reciben daño, cuando atacan a la furgoneta o estructuras, si no se puede colocar una estructura...
Pasos para reproducirlo: Acciones con el jugador.

**Comment by TheNidesRA** [comment]
Se ha solventado este problema introduciendo las siguientes características:
1. Efecto de partículas cuando el enemigo es derrotado.
2. Efecto de partículas al añadir una estructura.
3. Efecto de partículas y sonido al destruir una estructura.
4. Retroalimentación sonora de impacto de bala contra el enemigo.
5. La estructura se pone en rojo si no se puede construir en una zona del mapa.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA

TheNidesRA
