### ISSUE TITLE
[JUGABILIDAD] Vida de los enemigos. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#92]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Existe una barra de vida para el personaje principal pero no existe una para los enemigos. Es necesario saber la vida de los enemigos para poder crear estrategias y para saber cuándo se genera daño o cuando no, al igual que para verificar que se está lo está haciendo y cuánto les estás haciendo.
Pasos para reproducirlo: Jugar una ronda y hacer daño a los enemigos.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/f2616a7d8c2cc37da37808f0d15e9cbc3ee7acee, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
