### ISSUE TITLE
[JUGABILIDAD] Vida de las estructuras

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#93]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Al igual que con los enemigos, no existe una barra de vida para saber cuánto tiempo de vida le queda a cada estructura. Es necesario para saber cuándo es óptimo reparar una estructura, para saber cuándo y cuanto daño sufren.
Pasos para reproducirlo: Jugar una ronda y recibir daño.

**Comment by TheNidesRA** [comment]
Se ha eliminado la opción de reparar las estructuras puesto que no tenía utilidad en la versión beta existente actualmente.
Desde TheNides R.A., consideramos que la inclusión de barras de vida en las estructuras saturaría el mapa de información en pantalla ocultando, al colocar varias estructuras en el mapa, los modelos y su visualización.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
