### ISSUE TITLE
[JUGABILIDAD] Feedback de la tienda. 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#94]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: En la pantalla de la tienda, cuando se realiza cualquier tipo de interacción ella no se produce ningún tipo de feedback, hace que al jugador se pregunte si está roto el juego, si lo ha comprado o ha perdido su dinero.
Pasos para reproducirlo: seleccionar cualquier opción de la tienda.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/2577ef17c4bf8635a7bdb812a4bba69751df2bab, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
