### ISSUE TITLE
[JUGABILIDAD] Controles dentro del juego.

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#95]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Dentro del juego no hay nada de información sobre los controles de la partida. En el itch.io hay controles, pero al ser tantos, es inevitable que alguno se olvide.
Pasos para reproducirlo: Empezar el juego.

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/12f98faca1bbe6c040f155c8a014978267e7a0c8, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
