### ISSUE TITLE
[JUGABILIDAD] Falta de balanceo entre personajes  

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#96]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Los personajes están bastante desbalanceados, el hombre-cono es superior a los demás, dispara más rápido y da la sensación de que hace más daño. Cuando se juega con los otros dos se siente bastante injusto, sobre todo con Torrine, con ella es difícil ganar rondas. Apenas se notan características especiales, simplemente se percibe muy fácilmente cuáles son más potentes.
Pasos para reproducirlo: Jugar con todos los personajes.

**Comment by TheNidesRA** [comment]
Se ha balanceado todo el contenido del juego en varios commits. El commit final es el siguiente: https://github.com/TheNidesRA/FrozenFury/commit/4e1fe6dad20e2be21f4867059c4a0008e4f8b18

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
