### ISSUE TITLE
[JUGABILIDAD] Falta de balanceo entre enemigos y estructuras 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#97]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: El juego provoca que el balanceo entre los enemigos y las estructuras sea desigual. Para ganar la ronda, se depende demasiado del disparo del jugador. Las estructuras parece que no hacen el daño suficiente a los enemigos y tienen poca vida comparada con los enemigos que tienen mucha más vida y hacen mucho más daño a las estructuras. En caso de que se produzca la muerte del personaje, como tarda tanto en reaparecer, las estructuras no son capaces de proteger el camión.
Pasos para reproducirlo: Jugar una ronda, colocar estructuras y dejar que el personaje muera.

**Comment by TheNidesRA** [comment]
Se ha balanceado todo el contenido del juego en varios commits. El commit final es el siguiente: https://github.com/TheNidesRA/FrozenFury/commit/4e1fe6dad20e2be21f4867059c4a0008e4f8b188.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
