### ISSUE TITLE
[CONFORMIDAD] Las animaciones contra enemigos aéreos no se ejecutan

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#98]
Impacto: Alto.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: Hay en muchas ocasiones que no se llega a producir esta animación al disparar a los dos enemigos aéreos; el que más veces ha producido este error ha sido el dragón.
Pasos para reproducirlo: Disparar a los enemigos aéreos.

**Comment by TheNidesRA** [comment]
No se ha podido reproducir este error correctamente. Se necesita algo más de especificación, ya sea una foto o un vídeo.

¡Muchas gracias por ayudarnos a mejorar Frozen Fury!
TheNidesRA
