### ISSUE TITLE
[COMPATIBILIDAD] El juego no es responsive 

### ISSUE THREAD

**Issue by rox06io** [TheNidesRA/FrozenFury#99]
Impacto: Crítico.
Plataforma o entorno: PC/Móvil, Chrome/Mozilla.
Descripción: El juego no se puede probar si no es con la ventana maximizada o en pantalla completa. Esto hace que muchos botones no se vean.
Pasos para reproducirlo: Jugar con la ventana en mitad de la pantalla o con la pantalla ampliada (móvil).

**Comment by TheNidesRA** [comment]
Se ha solucionado este problema en el siguiente commit https://github.com/TheNidesRA/FrozenFury/commit/4a90f04dc5e102eb3148833bf592f24e768aa19f, así que procedemos a cerrar este problema.
¡Muchas gracias por ayudarnos a mejorar Frozen Fury!

TheNidesRA
